version: "3.9"
services:
    hello:
        build: ./api
        networks:
            - todo
    send:
        build: ./send
        depends_on: 
            rabbitmq:
                condition: service_healthy
        networks:
            - todo
    receive:
        build: ./receive
        depends_on: 
            rabbitmq:
                condition: service_healthy
        networks:
            - todo
    rabbitmq:
        image: rabbitmq:3-management-alpine
        volumes:
            - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
            - ./rabbitmq/logs:/var/log/rabbitmq/log
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
            - todo
    proxy:
        image: haproxy:2.3-alpine
        depends_on: 
            - hello
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - 81:80
        networks:
            - todo
volumes:
    logvolume01: {}

networks:
    todo: