version: "3.9"
services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - cluster.initial_master_nodes=es01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - /c/data/elasticsearch/todo-go:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana:7.13.2
        environment:
            ELASTICSEARCH_HOSTS: http://es01:9200
        ports:
            - 5601:5601
        depends_on: 
            - es01
        networks:
            - elastic
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.13.2
        user: root
        networks:
            - elastic
        volumes:
            - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
        environment:
            - ELASTICSEARCH_HOST=es01
        # disable strict permission checks
        command: ["--strict.perms=false"]
        depends_on: 
            - es01
volumes:
    logvolume01: {}

networks:
    elastic: