version: "3.9"
services:
    hello:
        build: ./api
        networks:
            - todo
    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    proxy:
        image: haproxy:2.3-alpine
        depends_on: 
            - hello
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        ports:
            - 81:80
        networks:
            - todo
volumes:
    logvolume01: {}

networks:
    todo: